### ISSUE TITLE
Wallet is not being removed correctly

### ISSUE THREAD

**Issue by rdk1979** [ArkEcosystem/mobile-wallet#174]
By accident I ran into the following bug:
After adding a second wallet from the main net I was unable to remove it:
- Enter wallet
- top right menu: "**Remove wallet**"
- "Are you sure?"   --> **Yes**

After doing that you jump to the mainscreen and only see your first wallet is still left. So far so good...
But... when you close your wallet app an login again with your pincode the wallet you removed is back again.

iOS version **11.4.1**
ARK wallet version **1.0.0**

**Comment by Hugoo** [comment]
I had the same problem but with the first wallet. When I delete it, I have the "empty wallet page" but when I kill / reopen the app, this wallet is back in the list. I had it several times but in my last attempt to delete it, it worked (not reappearing)

iOS version **11.4.1**
ARK wallet version **1.0.0**

**Comment by Hugoo** [comment]
Might be same problem as issue #1

**Comment by luciorubeens** [comment]
@alexbarnsley Can you reproduce? I had no problems to remove.

**Comment by alexbarnsley** [comment]
I can't reproduce either. Then again I am testing on up-to-date codebase @luciorubeens

**Comment by MoeB712** [comment]
Hello all. I'm having the same issue on Android wallet. However my scenario is a little different. I was having connection issues since network downtime 4 days ago, my main wallet doesn't re-synchronize and delegate list doesn't load. I tried to create a new profile with new wallet to see if I'm having the same connection issue. Here's what happened:

- Have my main profile with my main wallet on the profile list.
- Created a new 'test' profile and a new empty wallet.
- Opened the new 'test' profile. My new empty wallet shows up with 0 funds. So far so good.
- Tapped on the empty wallet it said fetching funds.
- Went back to the wallet screen and price chart page.
- My main wallet and my empty wallet now show up in my 'test' profile.
- Tried to delete my test wallet and it goes away.
- Tried to delete my main wallet it goes away but my test wallet comes back.
- Tried to delete my test wallet again and my main comes back.
- Exit and re-enter the app, both wallets come back in my 'test' profile.
- Can't delete 'test' profile either.

Once again, my mobile wallet can't re-synchronize (can't fetch new transactions and delegate list since the network downtime 4 days ago) so this might have some effect to this issue.
