### ISSUE TITLE
Bug when sending

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/mobile-wallet#33]
When I was sending I was able to tap the Send button twice while the app was thinking. I guess you should disable the Send button once tapped.

**Comment by zillionn** [comment]
I tapped several times Send but nothing was happening, then I decided to wait and this was the result

![screenshot_2018-01-01-19-00-04](https://user-images.githubusercontent.com/3462869/34469387-7efc7b96-ef26-11e7-8071-e503ffa63d19.png)

**Comment by ItsANameToo** [comment]
If I understand this issue correctly, then it should be applicable to every transition in the app. If you quickly tap a button twice (or if your phone hangs for a little bit and you can tap it again) the `navController.push(...)` function is called twice. The first one will navigate to the next screen, while the second call will crash as the screen it expects is no longer there (as the transition already happened). 

I think there would be two ways to solve this issue (any feedback would be appreciated):

1. Keep track of a variable that indicates when we are starting a transition (e.g. aboutToNavigate) and don't allow any new transition calls as long as that variable is set.
2. Catch the error that the navigation will throw when it is tapped twice

I believe this issue is also addressed [here](https://github.com/ionic-team/ionic/issues/11776), but so far it does not seem to be solved by the Ionic team.

@alexbarnsley @luciorubeens What do you think?

**Comment by alexbarnsley** [comment]
Sorry @ItsANameToo i missed your comment. Yes, I'm happy for something along those lines to be implemented unless @luciorubeens is aware of any other solution which may resolve.

**Comment by luciorubeens** [comment]
Closed via #188
